import { Inter, Vazirmatn } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css"
import MyApp from "@/_app";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const vazir = Vazirmatn({ subsets: ["arabic"],display:"swap" });
import 'react-confirm-alert/src/react-confirm-alert.css'

export const metadata = {
  title: "Food App",
  description: "Generated by Abnos",
};

const RootLayout = ({ children }) => {

  return (
    <html lang="fa" dir="rtl">
      <body className={vazir.className}>
        <MyApp>
            <Header/>
                {children}
            <Footer/>
        </MyApp>
      </body>
    </html>
  );
}

export default RootLayout
